#when preparing the model we need to set the parameters.
#In text_summarization.ipynb under trainer_args we are setting the parameters
#These are the parameters which the model uses to train.
TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1e6
  gradient_accumulation_steps: 16